### ISSUE TITLE
[Testing] Migrate to Cypress 10

### ISSUE THREAD

**Issue by AleksandarDev** [Enterwell/react-starter#228]
New version has some breaking changes. See [Changelog](https://docs.cypress.io/guides/references/changelog#10-0-0) for more info. There is guide available after cypress is updated to guide you through migration process.

**Comment by yoshitaka7** [comment]
Hi!! I found this project interesting and I would love to contribute to fixing this issue!

**Comment by yoshitaka7** [comment]
Hello, I have created a PR on this issue.
If you would like to, please take a look.
https://github.com/Enterwell/react-starter/pull/232
