### ISSUE TITLE
 [React] Migrate to React 18

### ISSUE THREAD

**Issue by AleksandarDev** [Enterwell/react-starter#229]

**Comment by OloyedeTobi** [comment]
Hello. I would love to contribute to fixing this issue!

**Comment by AleksandarDev** [comment]
> Hello. I would love to contribute to fixing this issue!

@OloyedeTobi 

Hi, feel free to open a PR. 
If there are any issues with migration you can ask here.

Cheers 👍

**Comment by AleksandarDev** [comment]
@OloyedeTobi Have you made any progress?
