### ISSUE TITLE
[Architecture] Helpers and services should be a collections of functions instead of classes

### ISSUE THREAD

**Issue by radovix** [Enterwell/react-starter#256]
Approach where helpers and services are not classes, but a collections of exported functions, should be considered. I think that could benefit the tree shaking process and reducing the bundle size.

**Comment by AleksandarDev** [comment]
Can we adapt this approach? Seems better to me and more inline with current React architecture.

**Comment by radovix** [comment]
I'm all for it. @DorijanH what's your opinion about this?

**Comment by DorijanH** [comment]
Yea, I'm all in for it. In newer projects, we already define helpers as collections of exported functions and it works okay, so I think it is time to change it in the starter aswell.

**Comment by radovix** [comment]
Mappers could probably be included as well. Since they don't include any state.
