### ISSUE TITLE
[Next] Migrate to app directory

### ISSUE THREAD

**Issue by AleksandarDev** [Enterwell/react-starter#400]
[Info about app directory](https://beta.nextjs.org/docs/routing/fundamentals)
[Migration guide](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app)

**Comment by DorijanH** [comment]
[Next.js 13.4](https://nextjs.org/blog/next-13-4) has been released and with it the App Router has finally been marked as stable!  🎉

Now we can move to the new router with a little more confidence
