### ISSUE TITLE
[Docs] Readme Cypress logo no longer working

### ISSUE THREAD

**Issue by AleksandarDev** [Enterwell/react-starter#401]
![image](https://user-images.githubusercontent.com/643171/219668418-2daba00d-d672-4b0f-a0b4-224de910dc4f.png)

**Comment by Dhananjay-12** [comment]
hi @AleksandarDev  i want to fix this

**Comment by AleksandarDev** [comment]
No longer needed due to 
https://github.com/Enterwell/react-starter/issues/399
