### ISSUE TITLE
[Storybook] Dodati storybook

### ISSUE THREAD

**Issue by mateikki** [Enterwell/react-starter#42]
- napraviti storybook da imamo pregled svih komponenti koje smo koristili u projektu, [link](https://storybook.js.org/)
- kako aleksdev kaže storybook ne radi dobro sa material UI al naš starter po defaultu valjda nema material UI pa možemo ubaciti storybook
- dokumentirati kako se dodaju nove komponente, šta sve treba napravit da se prikažu u storybooku, kako možemo vidjeti storybook itd.
- trenutno nemamo niti jednu komponentu u starteru pa nemamo šta ubacit u storybook. Možda napraviti još view sa favorite pokemonima, taj nek prikazuje listu pokemona koje smo odabrali u favoritese (nek se sprema u localstorage) - onda cemo listu pokemona imat ko komponentu za storbook. Razmisliti još ima li smisla i ove ostale stvari koje su nam sad div-ovi izbacit u komponente samo da pokažemo na njima kako radimo storybook i to sve

**Comment by AleksandarDev** [comment]
@DorijanH
